ARG OPENSTACK_RELEASE=2025.1
ARG BASE_TAG=${OPENSTACK_RELEASE}-ubuntu_noble

FROM docker.io/cloudification/horizon:2025.1-ubuntu_noble-20260324183048
ARG OPENSTACK_RELEASE
ARG CONSTRAINTS=https://raw.githubusercontent.com/openstack/requirements/stable/${OPENSTACK_RELEASE}/upper-constraints.txt
ARG CONSTRAINTS_2024_1=https://opendev.org/openstack/requirements/raw/branch/unmaintained/2024.1/upper-constraints.txt
ARG BARBICAN_UI_REF=main

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential python3-dev git && \
    pip install -c ${CONSTRAINTS_2024_1} octavia-dashboard && \
    pip install -c ${CONSTRAINTS} \
        "barbican-ui @ git+https://github.com/cloudification-io/barbican-ui.git@${BARBICAN_UI_REF}" && \
    apt-get purge -y build-essential python3-dev && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
